# Домашнее задание 1

Это домашнее задание посвящено базовой обработке данных, визуализации и построению тривиальных моделей прогнозирования. Данные взяты из реального проекта, поэтому будем считать условия приближенными к боевым. Весь код необходимо написать на Python. Источником данных будет файл hw_data_bad.xlsx. Он содержит некоторые временные ряды показателя Fact, разделённые на несколько типов (регион, тип цены и тип подсчёта). Что значат эти переменные разбирать не имеет смысла в текущей работе, но для любопытных ниже абзац с пояснениями, которые можно смело пропустить.

Fact - это некоторая премия за продажу определённого товара внутри рынка, а не за границу. Грубо говоря, выигрыш от продажи на внутреннем рынке. Понятное дело, что в зависимости от конъюнктуры эта премия может быть и отрицательной, так как возить за рубеж может быть выгоднее. Соответственно, region обозначает регион, где ведётся тогровля, price_type_fact - тип цены, по которой ведётся торговля, а calculation_type_fact - то, каким методом были получены цены. Эти три переменные нам будут нужны только для группировки данных и особого смысла они не несут.

Прочтите данные файла hw_data_bad.xlsx. Справедливый читатель воскликнет, мол, почему храним не в csv, это же эффективнее, проще и всё такое. Однако на практике с хранением временных данных в подавляющем большинстве случаев наблюдается полный бардак. Формат исходных данных почти не менялся. Однако, в некоторые места были добавлены аномалии. Что характерно, ни одна из них не была придумана, и такие приколы я реально встречал в данных. Пусть лучше вас к ним подготовит этот курс, чем реальные проекты. Для обработки данных запрещается использовать библиотеки кроме numpy, pandas и itertools. Запрещено использовать циклы, итерирующиеся по строкам.

На первом этапе необходимо получить датасет в том виде, в котором он представлен ниже. Далее я буду называть эту таблицу широкой, а исходную длинной.

In [72]:
data_merged

           КРАСНОДАРСКИЙ КРАЙ               СТАВРОПОЛЬСКИЙ КРАЙ
                   Прайс лист                        Прайс лист
                     реальные теоретические            реальные теоретические
date
2014-01-01           0.965049     14.002235          -24.399670    -23.784398
2014-02-01          -8.684666      6.498247          -20.353659    -18.814861
2014-03-01           5.822015     21.029383            9.989441     11.271208
2014-04-01          25.069292     39.978937           39.979936     41.449397
2014-05-01          31.190931     47.087003           36.037895     33.986323
2014-06-01          19.300962     35.467245           10.053674     14.472603
2014-07-01           8.602108     23.641095           -0.362005     -2.710165
2014-08-01         -11.787255      2.334720                 NaN           NaN
2014-09-01         -34.626354    -20.710176          -17.169063    -20.599000
2014-10-01         -20.057527     -6.687766           -8.261589     -8.531556
2014-11-01         -18.707664     -8.191713          -14.870282    -13.082283
2014-12-01         -40.032650    -31.322727                 NaN           NaN
2015-01-01         -91.327789    -85.324643          -82.855198    -80.984281
2015-02-01         -65.536879    -57.592923          -61.185610    -62.252309
2015-03-01         -30.864428    -22.438874          -24.663822    -24.872007
2015-04-01          33.112910     29.855917           41.853412     40.427918
2015-05-01          11.907077     29.244833           27.828553     26.308562
2015-06-01          -5.026167     10.999667           -2.560789     -2.353768
2015-07-01           0.599885      5.862273           13.260541     14.076698
2015-08-01         -16.391144    -14.529440                 NaN           NaN
2015-09-01         -11.559252     -6.792690           -5.265214     -5.370704
2015-10-01          -6.129461      1.013718           -3.232713     -3.390266
2015-11-01         -15.802905     -8.567963          -20.457190    -19.474732
2015-12-01                NaN           NaN          -27.068263    -26.084327
2016-01-01         -24.550705    -15.501483          -26.364824    -24.718715
2016-02-01          -4.700573      2.698261           -1.118766     -1.509479
2016-03-01          10.121237     20.119726           19.659421     19.387432
2016-04-01          25.316745     36.041445           30.155533     29.709486
2016-05-01          23.177747     29.976137           49.867508     49.494246
2016-06-01          13.028857     23.903220           31.019793     27.997000
2016-07-01          19.855634     30.944629           31.851300     31.042228
2016-08-01                NaN           NaN                 NaN           NaN
2016-09-01          -1.127661      5.871016            3.772240      0.496833
2016-10-01          -8.621704     -1.121565                 NaN           NaN
2016-11-01          -6.046745      4.343832                 NaN           NaN
2016-12-01                NaN           NaN           11.712349      8.262458
2017-01-01                NaN           NaN                 NaN           NaN
2017-02-01                NaN           NaN                 NaN           NaN
2017-03-01          -1.839946     15.758481           14.869807     15.302467
2017-04-01          28.007839     45.816769           28.743714     31.845361
2017-05-01          17.238291     35.283298           41.094270     41.499467
2017-06-01          17.611629     35.515053           41.397547     41.608985
2017-07-01          -4.771857      2.086793                 NaN           NaN
2017-08-01          -9.474486      3.197839            2.916265      3.619337
2017-09-01         -32.092731    -13.222109          -12.899085    -13.411735
2017-10-01         -22.382917     -8.832728          -16.462090    -16.852815
2017-11-01                NaN           NaN                 NaN           NaN
2017-12-01                NaN           NaN                 NaN           NaN
2018-01-01          18.684979     36.172484           21.157454     21.156522
2018-02-01           8.061281     25.663052           25.024977     24.953674
2018-03-01          25.797919     34.485899           28.954947     29.009280
2018-04-01          21.090116     29.457338           30.011962     26.193418
2018-05-01                NaN           NaN            6.898155      6.369193
2018-06-01                NaN           NaN                 NaN           NaN
2018-07-01         -24.206879    -15.266210          -19.782427    -21.523550
2018-08-01         -27.850696    -20.802422          -26.204440    -27.646785
2018-09-01                NaN           NaN                 NaN           NaN
2018-10-01          -8.608973      4.531917            5.322236      5.181332
2018-11-01           3.328259     18.489245            1.753096      1.642617

## Поиск аномалий (0 баллов)

Для начала поищите, собственно, аномалии в данных. Что это и как их искать я не скажу, однако вы их точно найдёте, пока будете приводить таблицу к нужному виду.

In [ ]:
# ༼ つ ◕_◕ ༽つ

## Обработка временных переменных (4 балла)

Далее необходимо разобраться с переменными, отвечающими за временную шкалу. Всё, что вам нужно для работы с временными переменными, вы найдёте по ссылке https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html. В конечном датафрейме столбец индексов имеет тип данных datetime64. Придумайте, как свести столбцы year и month в единый столбец date. Скорее всего вам будет здесь полезна функция pd.to_datetime, хотя и не обязательно. На семинаре мы обсуждали, что у временных данных есть периодичность (частотность, frequency) -- (год, месяц и т.д.) Однако, в pandas этот спектр не совсем такой. Нет понятия "месяц", но есть "начало месяца", "конец месяца" и т.п. (Смотри раздел Offset aliases). Из двух перечисленных выбирайте тот, к которму вам проще привести данные. В данном случае не обязательно присутствует какое-то супер-элегантное решение, но фантазия приветствуется. 

Также обратите внимание на полную временную шкалу финальной таблицы. Все ряды должны иметь одинаковую длину, поэтому шкала начинается от минимальной представленной в датасете до максимальной. Пригодится функция pd.date_range(). 

Помимо этого, в данных есть дыры. Месяцы идут подряд, но иногда с шагом. В конечных данных такого быть не должно, необходимо заполнить это пропусками. Делать это в исходном формате исходной "длинной" таблицы или конечной "широкой" таблицы не имеет значения. У меня получилось сделать это "на лету" при переходе от длинной таблицы к широкой.

Для полного балла ваш конечный результат должен полностью совпадать представленным выше.

In [ ]:
# ༼ つ ◕_◕ ༽つ

## Визуализация

### 2 балла

Постройте график в виде линий, на котором будут присутствовать все четыре временных ряда. Изобразите различные ряды разными цветами. Также добавьте на график среднее всех рядов, выделив его цветом и толщиной. В любом случае визуал скорее всего получится неприглядным из-за большого количества пропусков. 

Придумайте метод заполнения пропусков для этой задачи, принимая во внимание сезонность данных и то, что различные ряды схожи по структуре и своей сути. Повторите рисунок для заполненных рядов. Графики без осей/подписей и прочих очевидных атрибутов не оцениваются.

In [ ]:
# ༼ つ ◕_◕ ༽つ

### 1 балл

Что вы можете сказать о характеристиках временных рядов? Присутствует ли в рядах стационарность? Вы пока не умеете тестировать это, поэтому достаточно будет оценить "на глазок". Если нет, можете ли вы привести пример преобразования, которое сделает ряд стационарным? (Это мы также позже пройдём, пока достаточно просто попытаться предположить.) Есть ли в рядах сезонность? Как это повлияет на выбор модели?

In [ ]:
# ༼ つ ◕_◕ ༽つ

### 1 балл

Постройте сетку из четырёх scatter-plot, где каждая ячейка будет соответствовать одному из четырёх рядов. По оси $х - y_{t-1}$, по оси $y - y_t$. Какие выводы можно сделать о функциональной зависимости в данных и, как следствие, о подходящих моделях?

In [ ]:
# ༼ つ ◕_◕ ༽つ

## Прогнозирование

### 1 балл

Выберите один ряд, который вам больше нравится. Важно, чтобы к этому моменту в нём не осталось пропусков. Отделите от ряда последний год и сохраните его в качестве тестовой выборки. Далее на оставшейся тренировочной части постройте прогнозы наивной и сезонной наивной моделей на тот самый удалённый последний год. Можно пользоваться как готовыми реализациями, так и самописными.(Но имхо самому написать быстрее чем найти.) Визуализируйте исходный ряд и прогнозы на одном графике, обозначив их разными цветами.

In [ ]:
# ༼ つ ◕_◕ ༽つ

### 1 балл

Сравните прогнозы двух моделей, сравнив их с тестовой выборкой. В качестве метрики используйте MAPE. Для её корректной работы в случае нулевых значений можно децентрировать данные, прибавив к ним произвольную константу. Какая модель оказалась более эффективной? Как вы думаете, почему?

In [ ]:
# ༼ つ ◕_◕ ༽つ