In [22]:
import os
import pandas as pd
top = os.getcwd()

all_data = []
for root, dirs, files in os.walk(top):
     for file in files:
            if file.endswith('.csv'):
                all_data.append(pd.read_csv(file, index_col=0))

In [95]:
final_data = []
max_len = [30,60,156,315,500,720]
for data, max_length in zip(all_data, max_len):
    data = data.loc[(~data.isna()).sum(axis=1) > int(max_length*0.5), :]
    sample = data.sample(min(2000, len(data))).iloc[:,:max_length].T.reset_index(drop=True)
    sample.columns = [f'col_{i}' for i in range(sample.shape[1])]
    if np.max(sample.isna().sum()) != 0:
        sample = sample.iloc[:np.max(sample.isna().sum()),:]
    final_data.append(sample)

In [99]:
final_data[2]

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_1990,col_1991,col_1992,col_1993,col_1994,col_1995,col_1996,col_1997,col_1998,col_1999
0,2834.0,1070.0,307.0,1165.42,2589.24,1447.0171,5184.0,1964.21640,4520.0,2023.175,...,1190.926,1219.048,4740.0,1169.5,6400.0,2150.0,420.0,2370.0,4571.65119,1000.0
1,2821.0,1160.0,326.0,1183.43,1974.15,1453.8853,5198.0,1795.62995,4560.0,1838.708,...,1190.146,1309.163,4760.0,1210.5,6250.0,2150.0,420.0,6730.0,4778.08179,1001.0
2,2852.0,1060.0,367.0,1212.36,2589.24,1471.0254,5280.0,1741.72603,4610.0,1919.313,...,1212.607,1321.687,4810.0,1231.7,6350.0,2190.0,420.0,7510.0,4639.64954,961.0
3,2920.0,930.0,406.0,1234.47,2565.13,1473.6599,5253.0,1538.26491,4480.0,1457.645,...,1220.646,1303.865,4810.0,1305.9,6700.0,2230.0,380.0,3150.0,4898.43087,926.0
4,2980.0,1100.0,386.0,1252.06,1974.15,1478.3506,5259.0,1265.83522,4450.0,1237.775,...,1223.981,1337.835,4890.0,1316.6,7030.0,2260.0,550.0,6800.0,4499.52403,913.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,4452.0,2270.0,371.0,1562.51,3283.71,2083.3948,6565.0,3283.97210,4360.0,1911.782,...,2218.356,1338.368,5790.0,2676.2,6800.0,2410.0,690.0,1980.0,5267.97951,1136.0
73,4437.0,1290.0,630.0,1572.57,2724.38,2071.0570,6546.0,3138.91819,4470.0,2089.933,...,2271.578,1416.628,5810.0,2711.8,6820.0,2400.0,620.0,2140.0,5215.34932,1093.0
74,4453.0,2400.0,1008.0,1581.20,2387.25,2076.0316,6549.0,2924.29828,4530.0,2320.836,...,2303.700,1414.912,5850.0,2772.5,6940.0,2460.0,740.0,2540.0,5474.70948,1052.0
75,4419.0,1940.0,1047.0,1629.38,2909.90,2067.6437,6609.0,2719.82177,4580.0,2499.331,...,2331.079,1449.815,5820.0,2793.5,7300.0,2470.0,630.0,2660.0,5614.30782,1063.0
76,4439.0,1320.0,1047.0,1618.21,2724.38,2071.6526,6619.0,2316.79198,4630.0,1690.195,...,2391.819,1461.502,5890.0,2813.8,7830.0,2470.0,700.0,1930.0,5287.26207,1028.0

In [100]:
data_sample = {'Yearly': final_data[0], 'Quarterly': final_data[1],
          'Monthly': final_data[2], 'Weekly': final_data[3] , 'Daily': final_data[4], 'Hourly': final_data[5]}

for key in data_sample.keys():
    data_sample[key].to_csv(f'{key}_sample.csv')